runtime: ruby25

service: api

entrypoint: bundle exec rackup -s Puma -p $PORT

instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 20

includes:
  - app-secret-env.yaml
